/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class  */

#ifndef _Included_
#define _Included_
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
