/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_graphics_IntRect */

#ifndef _Included_org_jsfml_graphics_IntRect
#define _Included_org_jsfml_graphics_IntRect
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jsfml_graphics_IntRect_serialVersionUID
#define org_jsfml_graphics_IntRect_serialVersionUID -4430448425788537785LL
#ifdef __cplusplus
}
#endif
#endif
