/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_internal_StreamUtil */

#ifndef _Included_org_jsfml_internal_StreamUtil
#define _Included_org_jsfml_internal_StreamUtil
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jsfml_internal_StreamUtil_BUFFER_SIZE
#define org_jsfml_internal_StreamUtil_BUFFER_SIZE 16384L
#ifdef __cplusplus
}
#endif
#endif
