/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_internal_Const */

#ifndef _Included_org_jsfml_internal_Const
#define _Included_org_jsfml_internal_Const
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
