/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_system_Vector2i */

#ifndef _Included_org_jsfml_system_Vector2i
#define _Included_org_jsfml_system_Vector2i
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jsfml_system_Vector2i_serialVersionUID
#define org_jsfml_system_Vector2i_serialVersionUID 4059550337913883695LL
#ifdef __cplusplus
}
#endif
#endif
