/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_graphics_ConstFont_Info */

#ifndef _Included_org_jsfml_graphics_ConstFont_Info
#define _Included_org_jsfml_graphics_ConstFont_Info
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
