/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_graphics_VertexArray */

#ifndef _Included_org_jsfml_graphics_VertexArray
#define _Included_org_jsfml_graphics_VertexArray
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jsfml_graphics_VertexArray_MAX_ARRAY_SIZE
#define org_jsfml_graphics_VertexArray_MAX_ARRAY_SIZE 2147483639L
#undef org_jsfml_graphics_VertexArray_serialVersionUID
#define org_jsfml_graphics_VertexArray_serialVersionUID 8683452581122892189LL
#undef org_jsfml_graphics_VertexArray_DEFAULT_CAPACITY
#define org_jsfml_graphics_VertexArray_DEFAULT_CAPACITY 10L
#undef org_jsfml_graphics_VertexArray_MAX_ARRAY_SIZE
#define org_jsfml_graphics_VertexArray_MAX_ARRAY_SIZE 2147483639L
#undef org_jsfml_graphics_VertexArray_serialVersionUID
#define org_jsfml_graphics_VertexArray_serialVersionUID 4656221909265000727LL
#ifdef __cplusplus
}
#endif
#endif
