/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_system_Vector3f */

#ifndef _Included_org_jsfml_system_Vector3f
#define _Included_org_jsfml_system_Vector3f
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jsfml_system_Vector3f_serialVersionUID
#define org_jsfml_system_Vector3f_serialVersionUID -2176250005619169432LL
#ifdef __cplusplus
}
#endif
#endif
