/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_system_Clock */

#ifndef _Included_org_jsfml_system_Clock
#define _Included_org_jsfml_system_Clock
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
