/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_internal_SFMLNativeObject */

#ifndef _Included_org_jsfml_internal_SFMLNativeObject
#define _Included_org_jsfml_internal_SFMLNativeObject
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
