/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_window_event_MouseWheelEvent */

#ifndef _Included_org_jsfml_window_event_MouseWheelEvent
#define _Included_org_jsfml_window_event_MouseWheelEvent
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
