/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_graphics_TextStyle */

#ifndef _Included_org_jsfml_graphics_TextStyle
#define _Included_org_jsfml_graphics_TextStyle
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jsfml_graphics_TextStyle_REGULAR
#define org_jsfml_graphics_TextStyle_REGULAR 0L
#undef org_jsfml_graphics_TextStyle_BOLD
#define org_jsfml_graphics_TextStyle_BOLD 1L
#undef org_jsfml_graphics_TextStyle_ITALIC
#define org_jsfml_graphics_TextStyle_ITALIC 2L
#undef org_jsfml_graphics_TextStyle_UNDERLINED
#define org_jsfml_graphics_TextStyle_UNDERLINED 4L
#undef org_jsfml_graphics_TextStyle_STRIKE_THROUGH
#define org_jsfml_graphics_TextStyle_STRIKE_THROUGH 8L
#ifdef __cplusplus
}
#endif
#endif
