/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_graphics_BlendMode_Factor */

#ifndef _Included_org_jsfml_graphics_BlendMode_Factor
#define _Included_org_jsfml_graphics_BlendMode_Factor
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
