/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_audio_ConstSoundBuffer */

#ifndef _Included_org_jsfml_audio_ConstSoundBuffer
#define _Included_org_jsfml_audio_ConstSoundBuffer
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
