/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_graphics_Vertex */

#ifndef _Included_org_jsfml_graphics_Vertex
#define _Included_org_jsfml_graphics_Vertex
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jsfml_graphics_Vertex_serialVersionUID
#define org_jsfml_graphics_Vertex_serialVersionUID -5749297453247575018LL
#ifdef __cplusplus
}
#endif
#endif
