/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_system_Time */

#ifndef _Included_org_jsfml_system_Time
#define _Included_org_jsfml_system_Time
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jsfml_system_Time_serialVersionUID
#define org_jsfml_system_Time_serialVersionUID 7038088548302750096LL
#ifdef __cplusplus
}
#endif
#endif
