/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_window_event_JoystickMoveEvent */

#ifndef _Included_org_jsfml_window_event_JoystickMoveEvent
#define _Included_org_jsfml_window_event_JoystickMoveEvent
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
