/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_system_Vector2f */

#ifndef _Included_org_jsfml_system_Vector2f
#define _Included_org_jsfml_system_Vector2f
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jsfml_system_Vector2f_serialVersionUID
#define org_jsfml_system_Vector2f_serialVersionUID -2082611034304583379LL
#ifdef __cplusplus
}
#endif
#endif
