/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_system_Vector3i */

#ifndef _Included_org_jsfml_system_Vector3i
#define _Included_org_jsfml_system_Vector3i
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jsfml_system_Vector3i_serialVersionUID
#define org_jsfml_system_Vector3i_serialVersionUID -2260992069088589367LL
#ifdef __cplusplus
}
#endif
#endif
