/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_graphics_ShaderSourceException */

#ifndef _Included_org_jsfml_graphics_ShaderSourceException
#define _Included_org_jsfml_graphics_ShaderSourceException
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jsfml_graphics_ShaderSourceException_serialVersionUID
#define org_jsfml_graphics_ShaderSourceException_serialVersionUID -3042686055658047285LL
#undef org_jsfml_graphics_ShaderSourceException_serialVersionUID
#define org_jsfml_graphics_ShaderSourceException_serialVersionUID -3387516993124229948LL
#undef org_jsfml_graphics_ShaderSourceException_serialVersionUID
#define org_jsfml_graphics_ShaderSourceException_serialVersionUID -6514888818053624276LL
#ifdef __cplusplus
}
#endif
#endif
