/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_graphics_Color */

#ifndef _Included_org_jsfml_graphics_Color
#define _Included_org_jsfml_graphics_Color
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jsfml_graphics_Color_serialVersionUID
#define org_jsfml_graphics_Color_serialVersionUID -161207563051572152LL
#ifdef __cplusplus
}
#endif
#endif
