/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_graphics_FloatRect */

#ifndef _Included_org_jsfml_graphics_FloatRect
#define _Included_org_jsfml_graphics_FloatRect
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jsfml_graphics_FloatRect_serialVersionUID
#define org_jsfml_graphics_FloatRect_serialVersionUID -8603980852893951558LL
#ifdef __cplusplus
}
#endif
#endif
