/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_window_ContextSettings */

#ifndef _Included_org_jsfml_window_ContextSettings
#define _Included_org_jsfml_window_ContextSettings
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jsfml_window_ContextSettings_serialVersionUID
#define org_jsfml_window_ContextSettings_serialVersionUID -3658200233541780345LL
#ifdef __cplusplus
}
#endif
#endif
