/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_graphics_Transform */

#ifndef _Included_org_jsfml_graphics_Transform
#define _Included_org_jsfml_graphics_Transform
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jsfml_graphics_Transform_serialVersionUID
#define org_jsfml_graphics_Transform_serialVersionUID 3796964163848107663LL
#ifdef __cplusplus
}
#endif
#endif
