/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_graphics_TextureCreationException */

#ifndef _Included_org_jsfml_graphics_TextureCreationException
#define _Included_org_jsfml_graphics_TextureCreationException
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jsfml_graphics_TextureCreationException_serialVersionUID
#define org_jsfml_graphics_TextureCreationException_serialVersionUID -3042686055658047285LL
#undef org_jsfml_graphics_TextureCreationException_serialVersionUID
#define org_jsfml_graphics_TextureCreationException_serialVersionUID -3387516993124229948LL
#undef org_jsfml_graphics_TextureCreationException_serialVersionUID
#define org_jsfml_graphics_TextureCreationException_serialVersionUID -3423733954575177518LL
#ifdef __cplusplus
}
#endif
#endif
