/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_window_WindowStyle */

#ifndef _Included_org_jsfml_window_WindowStyle
#define _Included_org_jsfml_window_WindowStyle
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jsfml_window_WindowStyle_NONE
#define org_jsfml_window_WindowStyle_NONE 0L
#undef org_jsfml_window_WindowStyle_TITLEBAR
#define org_jsfml_window_WindowStyle_TITLEBAR 1L
#undef org_jsfml_window_WindowStyle_RESIZE
#define org_jsfml_window_WindowStyle_RESIZE 2L
#undef org_jsfml_window_WindowStyle_CLOSE
#define org_jsfml_window_WindowStyle_CLOSE 4L
#undef org_jsfml_window_WindowStyle_FULLSCREEN
#define org_jsfml_window_WindowStyle_FULLSCREEN 8L
#undef org_jsfml_window_WindowStyle_DEFAULT
#define org_jsfml_window_WindowStyle_DEFAULT 7L
#ifdef __cplusplus
}
#endif
#endif
