/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_window_ContextActivationException */

#ifndef _Included_org_jsfml_window_ContextActivationException
#define _Included_org_jsfml_window_ContextActivationException
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jsfml_window_ContextActivationException_serialVersionUID
#define org_jsfml_window_ContextActivationException_serialVersionUID -3042686055658047285LL
#undef org_jsfml_window_ContextActivationException_serialVersionUID
#define org_jsfml_window_ContextActivationException_serialVersionUID -3387516993124229948LL
#undef org_jsfml_window_ContextActivationException_serialVersionUID
#define org_jsfml_window_ContextActivationException_serialVersionUID -9207950728636532244LL
#ifdef __cplusplus
}
#endif
#endif
