/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_audio_SoundRecorderException */

#ifndef _Included_org_jsfml_audio_SoundRecorderException
#define _Included_org_jsfml_audio_SoundRecorderException
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jsfml_audio_SoundRecorderException_serialVersionUID
#define org_jsfml_audio_SoundRecorderException_serialVersionUID -3042686055658047285LL
#undef org_jsfml_audio_SoundRecorderException_serialVersionUID
#define org_jsfml_audio_SoundRecorderException_serialVersionUID -3387516993124229948LL
#undef org_jsfml_audio_SoundRecorderException_serialVersionUID
#define org_jsfml_audio_SoundRecorderException_serialVersionUID -6416178048026460236LL
#ifdef __cplusplus
}
#endif
#endif
