/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_internal_JSFMLError */

#ifndef _Included_org_jsfml_internal_JSFMLError
#define _Included_org_jsfml_internal_JSFMLError
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jsfml_internal_JSFMLError_serialVersionUID
#define org_jsfml_internal_JSFMLError_serialVersionUID -3042686055658047285LL
#undef org_jsfml_internal_JSFMLError_serialVersionUID
#define org_jsfml_internal_JSFMLError_serialVersionUID 4980196508277280342LL
#undef org_jsfml_internal_JSFMLError_serialVersionUID
#define org_jsfml_internal_JSFMLError_serialVersionUID -8281004117329430845LL
#ifdef __cplusplus
}
#endif
#endif
