/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jsfml_graphics_BlendMode */

#ifndef _Included_org_jsfml_graphics_BlendMode
#define _Included_org_jsfml_graphics_BlendMode
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jsfml_graphics_BlendMode_serialVersionUID
#define org_jsfml_graphics_BlendMode_serialVersionUID -384111167897124988LL
#ifdef __cplusplus
}
#endif
#endif
